"""Generate the preregistered 124M moving product-FHT c_proj screen."""

from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = ROOT / "examples" / "nanogpt" / "configs"
ARTIFACT_DIR = CONFIG_DIR / "selection_artifacts"
PARENT = (
    CONFIG_DIR
    / "y400_mai_v3_124m_fullattn_plus_mlp_cproj_"
    "muonchart154_0p5tpp_lr24e4.json"
)
STEM = (
    "y400_mai_v3_124m_fullattn_plus_mlp_cproj_"
    "productfht6_wsmuon_0p5tpp"
)
OUTPUT_ROOT = (
    "/root/userdata/MappingNetworks/outputs/"
    "y400_mai_v3_mlp_product_fht_screen"
)
SOURCE_PATHS = (
    "examples/nanogpt/model.py",
    "examples/nanogpt/muon.py",
    "examples/nanogpt/train.py",
    "latent_weight_lab/block_fht.py",
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def git_head() -> str:
    return subprocess.check_output(
        ["git", "rev-parse", "HEAD"],
        cwd=ROOT,
        text=True,
    ).strip()


def main() -> None:
    implementation_commit = git_head()
    source_hashes = {
        path: sha256(ROOT / path) for path in SOURCE_PATHS
    }
    config = json.loads(PARENT.read_text())
    config.update(
        {
            "out_dir": f"{OUTPUT_ROOT}/{STEM}",
            "hpo_stage": "cproj_product_fht_moving_tangent_0p5tpp",
            "ladder_slot": "cproj_productfht6_weight_space_muon",
            "ladder_role": "mlp_moving_tangent_causal_screen",
            "candidate_scope": (
                "accepted full-attention replacement plus mlp.c_proj "
                "generated by six fixed global signed-FHT mixers separated "
                "by learned channel diagonals; no learned dense basis, dense "
                "residual, or LoRA factors"
            ),
            "block_fht_muon_latent_targets": [],
            "block_fht_cproj_product_fht_factors": 6,
            "block_fht_cproj_product_fht_diagonal_scale": 1.0,
            "block_fht_cproj_product_fht_weight_space_muon": True,
            "block_fht_cproj_product_fht_natural_gradient": True,
            "implementation_commit": implementation_commit,
            "implementation_source_hashes": source_hashes,
            "mfu_preflight_certificate": (
                f"{OUTPUT_ROOT}/performance_preflight_{STEM}.json"
            ),
            "failed_mfu_preflight": None,
            "mfu_preflight_required": True,
            "mfu_min_fraction": 0.2,
            "launch_ready": True,
            "recipe_resolution_required": False,
            "recipe_resolution_stage": (
                "polar_direction_moving_tangent_smallest_rung"
            ),
            "recipe_resolution_dependency": (
                "exact dense-Muon probes found 16.4694 percent future-chord "
                "recovery from the applied polar update, while exact "
                "projection through the current fixed BlockFHT tangent "
                "collapsed recovery to 0.16745 percent"
            ),
            "selection_endpoint": (
                "terminal fixed-window validation CE versus the exact "
                "attention-only and fixed-tangent generated-c_proj controls"
            ),
            "preregistered_decision_rule": {
                "primary_metric": (
                    "terminal fixed-window validation cross entropy at "
                    "update 238"
                ),
                "attention_only_validation_ce": 5.4918,
                "fixed_tangent_cproj_validation_ce": 5.7395,
                "acceptable_attention_gap_ce": 0.1,
                "success": (
                    "stable candidate finishes at or below 5.5918 CE, "
                    "within +0.1000 of the accepted attention-only control"
                ),
                "directional_only": (
                    "stable candidate improves on 5.7395 CE but remains "
                    "above the +0.1000 attention-control gap"
                ),
                "reject": (
                    "candidate ties or regresses versus 5.7395 CE, is "
                    "unstable, fails the 20-percent MFU gate, or does not "
                    "complete"
                ),
            },
            "optimizer_assignment_expected": (
                "dense GPT matrices use Muon; attention BlockFHT latents and "
                "ordinary scalar parameters use the registered AdamW "
                "fallback; product-FHT diagonal factors use plain SGD after "
                "the cached materialized c_proj gradient is converted to the "
                "exact Muon polar direction and pulled back by exact VJP"
            ),
            "parent_fixed_tangent_config": str(PARENT.relative_to(ROOT)),
            "parent_fixed_tangent_config_sha256": sha256(PARENT),
            "moving_product_fht_parameterization": {
                "formula": (
                    "W = target_std*sqrt(padded_width)*"
                    "diag(exp(g_out))*P_out*D6*H*S6*...*D1*H*S1*P_in"
                ),
                "fixed_global_mixers": "normalized signed FHT",
                "learned_channel_diagonals": 6,
                "padded_width": 4096,
                "output_channels": 768,
                "trainable_scalars_per_layer": 25344,
                "materialized_weight_scalars_per_layer": 2359296,
                "trainable_fraction_per_cproj": (
                    25344 / 2359296
                ),
                "identity_diagonal_initialization": True,
                "gpt_residual_projection_std_matched": True,
                "moving_tangent": True,
                "learned_dense_basis": False,
                "dense_residual": False,
                "lora_adapter": False,
                "persistent_weight_space_momentum_scalars_per_layer": (
                    2359296
                ),
            },
            "weight_space_gradient_flow": {
                "order": [
                    "accumulate CE gradient on one cached materialized weight",
                    "update persistent materialized-weight momentum",
                    "apply the exact five-step Muon Newton-Schulz polar map",
                    "pull the polar direction back through the exact product-FHT VJP",
                    "apply diagonal generator-metric preconditioning",
                    "apply the registered global gradient clip",
                    "take a plain-SGD factor step with the main scheduled LR",
                ],
                "scale_note": (
                    "the polar map is invariant to positive scalar gradient "
                    "rescaling; applying it before the registered global clip "
                    "does not change its direction"
                ),
            },
            "direction_evidence": {
                "optimizer_state_result": (
                    "examples/nanogpt/configs/selection_artifacts/"
                    "124m_mlp_optimizer_state_direction_result.json"
                ),
                "blockfht_projection_result": (
                    "examples/nanogpt/configs/selection_artifacts/"
                    "124m_mlp_blockfht_polar_projection_result.json"
                ),
                "exact_applied_future_chord_recovery": 0.16469392843418235,
                "fixed_tangent_projected_future_chord_recovery": (
                    0.0016745042348182396
                ),
                "fixed_tangent_applied_energy_retained": (
                    0.010056494360673948
                ),
            },
            "screen_only_resolution": (
                "one 124M/0.5TPP causal run after a foreground-polled "
                "real-training 20-percent-MFU qualification"
            ),
            "monitoring_policy": (
                "the short MFU qualification and 238-step training run are "
                "polled directly; no watchdog, callback, queue heartbeat, or "
                "PRO6 execution"
            ),
            "prelaunch_provenance_requirements": (
                "record commit, source/config/dataset/fixed-eval hashes, "
                "literal command, exact host-local MFU certificate, status, "
                "log, and terminal checkpoint"
            ),
        }
    )
    config_path = CONFIG_DIR / f"{STEM}_lr24e4.json"
    config_path.write_text(
        json.dumps(config, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    config_hash = sha256(config_path)

    plan = {
        "schema_version": "mai_124m_mlp_product_fht_screen_plan_v1",
        "status": "preregistered_before_result",
        "candidate_config": str(config_path.relative_to(ROOT)),
        "candidate_config_sha256": config_hash,
        "implementation_commit": implementation_commit,
        "implementation_source_hashes": source_hashes,
        "hypothesis": (
            "a nonlinear product of fixed global FHT mixers and learned "
            "channel diagonals supplies a moving tangent that can preserve "
            "more of dense Muon's coherent polar direction than the rejected "
            "fixed BlockFHT tangent"
        ),
        "frozen_hyperparameters": {
            "product_fht_factors": 6,
            "diagonal_scale": 1.0,
            "weight_space_muon": True,
            "muon_momentum": 0.95,
            "muon_ns_steps": 5,
            "natural_gradient": True,
            "main_learning_rate": 0.0024,
            "adamw_fallback_scale": 0.3,
            "max_iters": 238,
            "tokens": 62390272,
        },
        "decision_rule": config["preregistered_decision_rule"],
        "launch_rule": (
            "do not launch unless this exact committed config passes a "
            "directly polled real-training MFU gate at or above 20 percent "
            "on Y400; train only on Y400 and poll directly"
        ),
    }
    plan_path = (
        ARTIFACT_DIR / "124m_mlp_product_fht_screen_plan.json"
    )
    plan_path.write_text(
        json.dumps(plan, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "config_path": str(config_path.relative_to(ROOT)),
                "config_sha256": config_hash,
                "plan_path": str(plan_path.relative_to(ROOT)),
                "plan_sha256": sha256(plan_path),
                "out_dir": config["out_dir"],
                "mfu_preflight_certificate": config[
                    "mfu_preflight_certificate"
                ],
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
