"""Generate the corrected 124M product-FHT c_proj screen."""

from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = ROOT / "examples" / "nanogpt" / "configs"
ARTIFACT_DIR = CONFIG_DIR / "selection_artifacts"
PARENT = (
    CONFIG_DIR
    / "y400_mai_v3_124m_fullattn_plus_mlp_cproj_"
    "productfht6_wsmuon_0p5tpp_lr24e4.json"
)
STEM = (
    "y400_mai_v3_124m_fullattn_plus_mlp_cproj_"
    "productfht6_wsmuon_jvpnorm_0p5tpp_lr24e4"
)
OUTPUT_ROOT = (
    "/root/userdata/MappingNetworks/outputs/"
    "y400_mai_v3_mlp_product_fht_jvpnorm_screen"
)
SOURCE_PATHS = (
    "examples/nanogpt/model.py",
    "examples/nanogpt/muon.py",
    "examples/nanogpt/train.py",
    "latent_weight_lab/block_fht.py",
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def git_head() -> str:
    return subprocess.check_output(
        ["git", "rev-parse", "HEAD"],
        cwd=ROOT,
        text=True,
    ).strip()


def main() -> None:
    implementation_commit = git_head()
    source_hashes = {
        path: sha256(ROOT / path) for path in SOURCE_PATHS
    }
    config = json.loads(PARENT.read_text())
    config.update(
        {
            "out_dir": f"{OUTPUT_ROOT}/{STEM}",
            "hpo_stage": (
                "cproj_product_fht_moving_tangent_jvpnorm_0p5tpp"
            ),
            "ladder_slot": (
                "cproj_productfht6_weight_space_muon_jvpnorm"
            ),
            "ladder_role": "mlp_moving_tangent_causal_screen",
            "candidate_scope": (
                "accepted full-attention replacement plus mlp.c_proj "
                "generated by six fixed global signed-FHT mixers and "
                "learned channel diagonals; exact materialized Muon VJP is "
                "JVP-norm calibrated without a learned dense basis, dense "
                "residual, or LoRA factors"
            ),
            "block_fht_cproj_product_fht_pullback_normalize": True,
            "block_fht_cproj_product_fht_pullback_max_coordinate_update": (
                0.02
            ),
            "block_fht_cproj_product_fht_pullback_probe": False,
            "block_fht_cproj_product_fht_pullback_probe_output": None,
            "implementation_commit": implementation_commit,
            "implementation_source_hashes": source_hashes,
            "mfu_preflight_certificate": (
                f"{OUTPUT_ROOT}/performance_preflight_{STEM}.json"
            ),
            "failed_mfu_preflight": None,
            "launch_ready": True,
            "monitoring_policy": (
                "run the exact performance gate and the 238-step candidate "
                "synchronously on one idle Y400 GPU; poll directly with no "
                "watchdog, callback, queue worker, or PRO6 execution"
            ),
            "parent_rejected_result": (
                "examples/nanogpt/configs/selection_artifacts/"
                "124m_mlp_product_fht_screen_result.json"
            ),
            "pullback_calibration_result": (
                "examples/nanogpt/configs/selection_artifacts/"
                "124m_mlp_product_fht_pullback_calibration_result.json"
            ),
            "pullback_calibration_evidence": {
                "actual_to_target_update_norm_ratio_minimum": (
                    0.9973294734954834
                ),
                "actual_to_target_update_norm_ratio_maximum": (
                    1.002163052558899
                ),
                "actual_target_update_cosine_minimum": (
                    0.09900259971618652
                ),
                "maximum_coordinate_update": 0.01534760284423828,
                "registered_coordinate_cap": 0.02,
                "calibration_probe_sha256": (
                    "870e1bf9f37deecd6578efee08e25ed7ce6afe30c4e8ebb8125bfba438815871"
                )
            },
            "weight_space_gradient_flow": {
                "order": [
                    "accumulate CE gradient on one cached materialized weight",
                    "update persistent materialized-weight momentum",
                    "apply the exact five-step Muon Newton-Schulz polar map",
                    "pull the polar direction back through the exact product-FHT VJP",
                    "apply diagonal generator-metric preconditioning",
                    "compute exact closed-form JVP of the preconditioned factor direction",
                    "normalize JVP Frobenius norm to the materialized Muon direction",
                    "cap maximum factor-coordinate update at 0.02",
                    "clip all non-product parameters at the registered global threshold",
                    "take a plain-SGD product-factor step with the scheduled main LR"
                ],
                "global_clip_note": (
                    "normalized product factors are excluded because the "
                    "one-step probe measured a 0.372 clip scale that would "
                    "otherwise invalidate materialized-step calibration"
                )
            }
        }
    )
    config_path = CONFIG_DIR / f"{STEM}.json"
    config_path.write_text(
        json.dumps(config, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    config_hash = sha256(config_path)
    plan = {
        "schema_version": (
            "mai_124m_mlp_product_fht_jvpnorm_screen_plan_v1"
        ),
        "status": "preregistered_before_result",
        "candidate_config": str(config_path.relative_to(ROOT)),
        "candidate_config_sha256": config_hash,
        "implementation_commit": implementation_commit,
        "implementation_source_hashes": source_hashes,
        "hypothesis": (
            "the first product-FHT endpoint was rejected because c_proj "
            "weights stayed almost frozen; exact JVP norm calibration now "
            "makes the selected learning rate a meaningful test of whether "
            "the nonlinear moving tangent can improve over the fixed tangent"
        ),
        "frozen_hyperparameters": {
            "product_fht_factors": 6,
            "diagonal_scale": 1.0,
            "weight_space_muon": True,
            "muon_momentum": 0.95,
            "muon_ns_steps": 5,
            "natural_gradient": True,
            "pullback_normalize": True,
            "pullback_max_coordinate_update": 0.02,
            "main_learning_rate": 0.0024,
            "adamw_fallback_scale": 0.3,
            "global_clip_non_product_only": 1.0,
            "max_iters": 238,
            "tokens": 62390272
        },
        "calibration_result": {
            "path": config["pullback_calibration_result"],
            "probe_sha256": (
                config["pullback_calibration_evidence"][
                    "calibration_probe_sha256"
                ]
            ),
            "movement_gate_passed": True
        },
        "decision_rule": config["preregistered_decision_rule"],
        "launch_rule": (
            "do not launch unless this exact committed config passes a fresh "
            "directly polled real-training MFU gate at or above 20 percent "
            "on Y400; poll the 238-step run directly"
        )
    }
    plan_path = (
        ARTIFACT_DIR / "124m_mlp_product_fht_jvpnorm_screen_plan.json"
    )
    plan_path.write_text(
        json.dumps(plan, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "config_path": str(config_path.relative_to(ROOT)),
                "config_sha256": config_hash,
                "plan_path": str(plan_path.relative_to(ROOT)),
                "plan_sha256": sha256(plan_path),
                "mfu_preflight_certificate": config[
                    "mfu_preflight_certificate"
                ]
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
